services:
  postgres:
    image: postgres:17.2
    container_name: finlet_postgres
    environment:
      POSTGRES_DB: "finlet"
      POSTGRES_USER: "finlet"
      POSTGRES_PASSWORD: "finlet"
      PGDATA: "/var/lib/postgresql/data/data"
    ports:
      - "5432:5432"
